apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpledemo
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  selector:
    matchLabels:
      app: simpledemo
  template:
    metadata:
      labels:
        app: simpledemo
    spec:
      containers:
      - name: simpledemo
        image: torumakabe/simpledemo:v1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: simpledemo
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: tomakabesimpledemo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: simpledemo